// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ContextVictorious))]
    [Migration("20191118185732_18112019")]
    partial class _18112019
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AplicationCore.Entity.Cargo", b =>
                {
                    b.Property<int>("CargoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("CargoId");

                    b.ToTable("tbCargo");
                });

            modelBuilder.Entity("AplicationCore.Entity.Membro", b =>
                {
                    b.Property<int>("MembroId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CEP")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<int?>("CargoId");

                    b.Property<string>("Cidade")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Numero");

                    b.Property<string>("Profissao")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UF")
                        .HasColumnType("varchar(3)");

                    b.HasKey("MembroId");

                    b.ToTable("tbMembro");
                });

            modelBuilder.Entity("AplicationCore.Entity.MembroTelefone", b =>
                {
                    b.Property<int>("MembroTelefoneId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MembroId");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoTelefone")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("MembroTelefoneId");

                    b.HasIndex("MembroId");

                    b.ToTable("tbMembroTelefone");
                });

            modelBuilder.Entity("AplicationCore.Entity.MembroTelefone", b =>
                {
                    b.HasOne("AplicationCore.Entity.Membro", "Membro")
                        .WithMany("Telefones")
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
